name: CI

on:
  pull_request:
    branches: [ main, master, prod ]

jobs:
  int-e2e-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: postgres
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: projectdb

    steps:
      - uses: actions/checkout@v3    
      - uses: actions/setup-node@v3   
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci  
      - run: npx prisma generate --schema ./src/shared/infraestructure/database/prisma/schema.prisma
        env:
          DATABASE_URL: "postgresql://postgres:docker@localhost:5432/projectdb?schema=test"
      - run: npx prisma migrate dev --schema ./src/shared/infraestructure/database/prisma/schema.prisma
        env:
          DATABASE_URL: "postgresql://postgres:docker@localhost:5432/projectdb?schema=test"
      - run: npm run test:int
        env:
          PORT: 3000
          NODE_ENV: test
          JWT_SECRET: test_secret
          JWT_EXPIRES_IN: 86400
          DATABASE_URL: "postgresql://postgres:docker@localhost:5432/projectdb?schema=test"
      - run: npm run test:e2e
        env:
          PORT: 3000
          NODE_ENV: test
          JWT_SECRET: test_secret
          JWT_EXPIRES_IN: 86400
          DATABASE_URL: "postgresql://postgres:docker@localhost:5432/projectdb?schema=test"
          